server {
    listen 8080;
    server_name wisp;

    # wisp_test_suite contains static files that need be served
    location / {
        root ./wisp_test_site;
    }

    # proxy is set to redirect to server running on port 3000
    location /api/ {
        proxy_pass http://127.0.0.1:3000;
    }
}